version: '3.9'  # Docker Compose file format version. 3.9 is compatible with modern Docker features.

services:  # Defines the services to be managed by Docker Compose.
  mongodb:  # Name of the first service (MongoDB database).
    image: mongo:latest  # Uses the official MongoDB image from Docker Hub.
    container_name: mongodb  # Sets a custom name for the MongoDB container.
    ports:
      - "27017:27017"  # Maps port 27017 on the host to port 27017 in the container (MongoDB's default port).
    volumes:
      - mongodb_data:/data/db  # Attaches a named volume 'mongodb_data' to persist data in /data/db (MongoDB's data directory).

  migration:  # Name of the second service (Python script for data migration).
    build:  # Specifies how to build the image for this service.
      context: .  # Uses the current directory as the build context.
      dockerfile: Dockerfile  # Specifies the Dockerfile to build the image (Python script's container).
    container_name: mongodb-migration  # Sets a custom name for the migration container.
    depends_on:  # Ensures the 'mongodb' service starts before 'migration'.
      - mongodb
    volumes:
      - ./healthcare_dataset.csv:/app/healthcare_dataset.csv  # Mounts the healthcare_dataset.csv file into the container at /app/healthcare_dataset.csv.

volumes:  # Defines named volumes for data persistence.
  mongodb_data:  # A named volume to persist MongoDB data.
